[[redirects]]
from = "/"
to = "/index.html"
status = 200

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/scripts/*"
to = "/scripts/:splat"
status = 200

[[redirects]]
from = "/styles/*"
to = "/styles/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true
